image: newlogic/deploy:lithium-php8.5

variables:
  ENVIRONMENT: production
  TESTS_BUILD: '["eslint", "stylelint"]'

build:
  stage: build
  artifacts:
    paths:
      - public/
    expire_in: 1 week
  cache:
    paths:
      - node_modules/

  before_script:
    - npm ci

  script:
    - node $HOME/.gitlab-ci/v2/tests-build.mjs
    - npm run build
